#!/usr/bin/env bash
# Bash script that will display information about subdomains.
if [ $# -eq 1 ]
then
	domi="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
	domi="$2.$1"
fi
dig $domi | awk '/ANSWER SECTION:/ { getline; split($1, sub, "."); print "The subdomain", sub[1], "is a", $4 " record and points to", $5}'
