#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i '/listen \[::\]:80 default_server;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_error.html
sudo sed -i '/listen 80 default_server/a error_page 404; location = {root /usr/share/nginx/html/404_error.html;/n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
