#!/usr/bin/env bash
# install nginx, setup customs headers
apt-get -y update
apt-get -y install nginx
sudo sed -i "\\\tadd_header X-Served-by $HOSTNAME;\n" /etc/nginx/sites-available/default
service nginx restart
