#!/usr/bin/env bash
# INSTALLING HAPROXY
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend diegoholberton.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 3335-web-01 34.148.151.72:80\n\tserver 3335-web-02 35.227.29.83:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
